### ISSUE TITLE
cancelation for our various index calls

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1362] opened 2019-06-24 15:22 UTC

**Comment by robert-milan** [comment] 2019-06-26 05:20
To further expand upon this, we don't currently pass the context into the index, so once an operation has started it runs until it is complete, even if the request was canceled. This is a waste of resources.

**Comment by fkaleo** [comment] 2020-01-27 13:40
dupe of #514

**Closed by fkaleo** 2020-01-27 13:40 UTC
