### ISSUE TITLE
Graphite-web: too strict validation for groupByNode[s], aggregate

### ISSUE THREAD

**Issue by robert-milan** [grafana/metrictank#1505] opened 2019-10-22 10:31 UTC
Graphite-web allows the use of render functions in some callbacks which only take aggregators. It accomplishes this by stripping off the `Series` part of the function, thus creating an alias for already existing aggregator functions. We are currently rejecting possibly valid queries that use this method.

https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.aggregate
https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.maxSeries

Possible solutions already discussed:
1. Add the `Series` versions to the `aggFuncAliases`
2. Implement it the same way graphite-web does

**Comment by Dieterbe** [comment] 2019-10-28 14:13
we need to look into whether this a bug in graphite AND/OR MT?

**Comment by woodsaj** [comment] 2019-10-28 17:30
I am confused by what the problem is.  The issue title makes it sound like graphite queries support something like
`aggregate('some.metric.*', maxSeries('something.foo.*'))`

But i think the problem is simply that graphite allows using the various aggregation function **names** as the 'func' to use for the aggregation.

**Comment by Dieterbe** [comment] 2019-10-28 21:02
Roberts problem was that a query like `groupByNode(consolidateBy(tsdb-gw.aggstats.*ops*.api.request.metrics.latency.max.gauge32, 'max'), 7, 'maxSeries')`
resulted in a http 400 response with body `Bad Request: Invalid option specified for function "groupByNode" parameter "callback"`
There's 2 ways to tell this comes from graphite, not metrictank:
* metrictank doesn't support `groupByNode` yet, so forwards to graphite
*
```
> r 'Invalid option specified for function' code/graphite-web
code/graphite-web/webapp/graphite/functions/params.py
141:        'Invalid option specified for function "{func}" parameter "{param}"'.format(
> r 'Invalid option specified for function' go/src/github.com/grafana/metrictank
>                                                                                   
```
we started running into this after deploying the validation option for graphite-web.
This ticket should have been a graphite issue. I have opened https://github.com/graphite-project/graphite-web/issues/2508 to replace this one.

I see no evidence of metrictank having this problem (it helps that MT currently doesn't support groupByNode or aggregate)

But as we can't assume that we can use our milestones to the graphite-web project, i propose we just keep using this ticket as a link to the graphite one.

**Comment by replay** [comment] 2019-12-18 13:04
With the recently merged PR https://github.com/graphite-project/graphite-web/pull/2513 the above examples should all work even with the input validation enabled, because all aggregator functions and their alias with the `+ 'Series'` suffix are accepted now. 

One thing which is still weird is the fact that in the code of the functions `groupByNode, groupByNodes, groupByTags` expects that the given aggregator function could also be any series processing function, like for example `groupByNodes(some.id.of.a.metric.*, "weightedAverage")`:
https://github.com/graphite-project/graphite-web/blob/52c0fd11a18de633e28e389d394ceba45a8e2831/webapp/graphite/render/functions.py#L4888
This is not documented, but the code appears to support that, even though in the case of most series processing functions it either doesn't work because the given arguments in the function call don't match what the series processing function expects, the return type of the series processing function doesn't match what the call site expects, or the result just makes no sense.
The specific example with `weightedAverage` doesn't work because the weighted average function call requires more arguments than only a list of series, resulting in a 5xx when it is used as an aggregator. On the other hand for example the series processing function `asPercent` works as an aggregator because it satisfies these 3 criteria:

1) First argument is a list of series
2) All other arguments are not required
3) Returns a list of series

So I'm worried some users might already be using series processing functions such as `asPercent` as aggregators, even though the support for this is not documented.
The problem for the input validation is that the criteria 1) and 2) can be detected by the input validation, but 3) cannot be detected because in Python there seems to be no practical way to obtain the return type from a defined function. As of the PR #2513 the input validation simply prohibits the use of any series processing functions as aggregators, including those few which might actually work and make sense like the example of `asPercent`.

I think if we want to also allow these series processing functions for which it makes sense as aggregators then we have 3 options:

1) Detect whether the expected list of arguments of each series processing function matches what the call site would pass it, and only allow those. This would remove most of the series processing functions from the list of allowed aggregators, meaning the input validation would be able to prevent a 5xx if a user tries to use them, but there are still going to be a few where the returned type doesn't match what the call site expects, resulting in a 5xx. This would mean that the input validation could not prevent all possible 5xx errors due to bad user input anymore, I have a PR where I tested that here: 
https://github.com/graphite-project/graphite-web/pull/2523
2) Go through the list of built-in series processing functions and manually pick the ones which can be used as an aggregator and mark them somehow, by setting some `.aggregator=True` property, that way the input validation could judge based on this property whether a series processing function may be used as aggregator. But this has the disadvantage that custom functions which have been created by users might not work as aggregators anymore, until they get updated to have that property.
3) The reverse of 2), which  would be to mark all those series processing functions which should not be used as aggregator functions with some property like `.aggregator=False`. That way the input validation could still detect whether the built-in series processing functions may be used as aggregators and then the default assumption would be that user defined custom functions may also be used as aggregators unless they're marked with that new property.

What do you think @DanCech

**Comment by replay** [comment] 2019-12-23 20:39
This is currently blocked on my question at https://github.com/graphite-project/graphite-web/issues/2508#issuecomment-567024155
If that conclusion regarding the issue I'm raising is going to be that we won't make any further changes at the moment, then this issue can be closed, but I'm waiting for feedback there.

**Comment by replay** [comment] 2020-01-20 17:45
Done, as https://github.com/graphite-project/graphite-web/pull/2528 is merged

**Closed by replay** 2020-01-20 17:45 UTC
Labels: bug
